import json,pathlib,ast,re
R=pathlib.Path(__file__).resolve().parents[1]
d=json.load(open(R/'data/latest.json'))
checks=[]
def ok(n,c): checks.append((n,bool(c)))
ok('product',d['meta']['product']=='BondStats Daily Signal Brief')
ok('copyright method', 'no third-party news' in d['meta']['copyrightMethod'].lower())
ok('methodology no news scraping', any('No news articles' in x for x in d['methodology']))
ok('archive exists',(R/'data/archive'/f"{d['meta']['date']}.json").exists())
ok('archive manifest',(R/'data/archive.json').exists())
ok('required source health',all(k in d['meta']['sourceHealth'] for k in ['macro','policy','calendar','yields']))
ok('signals list',isinstance(d['signals'],list))
ok('dislocations list',isinstance(d['dislocations'],list))
ok('events list',isinstance(d['nextEvents'],list))
ok('policy list',isinstance(d['nextPolicy'],list))
ok('daily markets only',all(x.get('freshDaily') for x in d['markets']))
ok('no causal language engine', 'assigning a news-driven cause' in (R/'scripts/update_brief.py').read_text())
ok('official macro links',all((not x.get('sourceUrl')) or x['sourceUrl'].startswith('https://') for x in d['macro']))
wf=(R/'.github/workflows/update-daily-brief.yml').read_text()
ok('manual run','workflow_dispatch' in wf);ok('daily cron',re.search(r"cron:\s*'37 6 \* \* \*'",wf));ok('write permission','contents: write' in wf);ok('tests before commit',wf.index('python tests/test_brief.py')<wf.index('git commit'))
html=(R/'index.html').read_text();ok('mobile responsive','@media(max-width:760px)' in html);ok('halo identity','class="halo"' in html);ok('archive UI',(R/'archive.html').exists() and (R/'brief.html').exists())
ast.parse((R/'scripts/update_brief.py').read_text());ok('updater syntax',True)
for n,c in checks: print(('PASS' if c else 'FAIL'),n)
if not all(c for _,c in checks): raise SystemExit(1)
print(f'ALL {len(checks)} TESTS PASSED')
