import ast, json, pathlib, re
R = pathlib.Path(__file__).resolve().parents[1]
d = json.load(open(R / 'data/latest.json', encoding='utf-8'))
checks = []
def ok(name, condition): checks.append((name, bool(condition)))

ok('v2 product', d['meta']['product'] == 'BondStats Daily Signal Brief' and d['meta']['version'].startswith('2.'))
ok('signal engine', d['meta'].get('engine') == 'BondStats Signal Engine v2')
ok('copyright architecture', 'no third-party news articles' in d['meta']['copyrightMethod'].lower())
ok('no-news methodology', any('news articles' in x.lower() and 'rewrit' in x.lower() for x in d['methodology']))
ok('no consensus fabrication', any('consensus' in x.lower() for x in d['methodology']))
ok('one thing', all(k in d['oneThing'] for k in ['headline','body','score','tag']))
ok('one thing score bounds', 0 <= d['oneThing']['score'] <= 100)
ok('signal stack five', len(d['signalStack']) == 5)
ok('signal memory', all(k in d['signalMemory'] for k in ['previousState','consecutiveDays','archiveObservations']))
ok('market state intensity', 0 <= d['marketState']['intensity'] <= 100)
ok('diagnostics complete', all(k in d['diagnostics'] for k in ['rates','macro','policy','eventRisk']))
ok('source integrity', d['meta']['sourceIntegrity']['total'] == 4)
ok('source health detailed', all(isinstance(v, dict) and 'status' in v for v in d['meta']['sourceHealth'].values()))
ok('signals list', isinstance(d['signals'], list))
ok('signal scores bounded', all(0 <= x.get('strength',0) <= 100 for x in d['signals']))
ok('dislocations list', isinstance(d['dislocations'], list))
ok('daily markets only', all(x.get('freshDaily') and x.get('changeBp') is not None for x in d['markets']))
ok('official/source macro links', all((not x.get('sourceUrl')) or x['sourceUrl'].startswith('https://') for x in d['macro']))
ok('archive immutable day exists', (R/'data/archive'/f"{d['meta']['date']}.json").exists())
manifest = json.load(open(R/'data/archive.json', encoding='utf-8'))
ok('archive manifest v2', manifest.get('version','').startswith('2.') and isinstance(manifest.get('days'), list))
ok('archive UI', (R/'archive.html').exists() and (R/'brief.html').exists())
ok('methodology UI', (R/'methodology.html').exists())
ok('homepage widget', (R/'widget.html').exists())
ok('health UI', (R/'health.html').exists())

script = (R/'scripts/update_brief.py').read_text(encoding='utf-8')
ok('no causality invention', 'Causality is not inferred' in script)
ok('fresh daily guard', 'stale <= 7' in script and 'frequency == "daily"' in script and 'isFallback' in script)
ok('source retries', 'attempts: int = 3' in script)
ok('fallback snapshots', 'last-known-good' in script.lower())
ok('immutable archive code', 'if not archive_path.exists()' in script)
ok('macro delta against archive', 'prior archived brief' in script.lower())
ok('archive rarity engine', 'percentile' in script and 'history_move_stats' in script)
ok('quiet is signal', 'Quiet is a signal' in script)
ast.parse(script); ok('updater syntax', True)

wf = (R/'.github/workflows/update-daily-brief.yml').read_text(encoding='utf-8')
ok('manual run', 'workflow_dispatch' in wf)
ok('daily cron', bool(re.search(r"cron:\s*'37 6 \* \* \*'", wf)))
ok('write permission', 'contents: write' in wf)
ok('concurrency protection', 'concurrency:' in wf and 'cancel-in-progress: false' in wf)
ok('tests before commit', wf.index('python tests/test_brief.py') < wf.index('git commit'))
ok('visible workflow copy', (R/'workflow-files/update-daily-brief.yml').exists())

html = (R/'index.html').read_text(encoding='utf-8')
ok('responsive UI', '@media(max-width:820px)' in html and '@media(max-width:470px)' in html)
ok('halo identity', 'class="halo"' in html and '--intensity' in html)
ok('one thing UI', 'THE ONE THING' in html)
ok('signal memory UI', 'Today in context' in html)
ok('source integrity UI', 'SOURCE' in html and 'integrityBadge' in html)
ok('originality disclosure', 'does not ingest, scrape, copy, summarize or rewrite third-party news' in html)
ok('copyright retained', '© 2026 BondStats Ltd. All rights reserved.' in html)
ok('no third party publisher names in UI', not any(x in html for x in ['Reuters','Bloomberg','Financial Times','CNBC','Wall Street Journal']))

for name, passed in checks:
    print(('PASS' if passed else 'FAIL'), name)
if not all(p for _, p in checks):
    raise SystemExit(1)
print(f'ALL {len(checks)} TESTS PASSED')
